### ISSUE TITLE
앱 재실행 시 항상 최신 정보로 갱신하는 현상

### ISSUE THREAD

**Issue by cwpark1993** [SerenityS/MyPIU#27]
https://github.com/SerenityS/MyPIU/blob/82aba360751bef620edf6a22c4a710415284231a/lib/presentation/play_data/view_models/my_data_view_model.dart#L35

해당 라인의 조건문에 문제가 있어보입니다.
총 클리어 카운트를 계산하는 부분 디버깅이 필요합니다.

**Comment by SerenityS** [comment]
안녕하세요, 우선 이슈 보고에 감사 드립니다.

제 계정에서는 문제가 일어나지 않는다는 점을 토대로..
PR(#28) 남겨주신 부분의 로직을 점검하며 문제를 일으켰을 것으로 추측되는 부분을 발견하였습니다.

https://github.com/SerenityS/MyPIU/blob/82aba360751bef620edf6a22c4a710415284231a/lib/data/repositories_impl/play_data_repository_impl.dart#L119

COOP 채보의 경우 level을 (0 + 인원 수, 3인 코옵 == 03레벨) 으로 지정하게 되는데.. 이 떄문에

https://github.com/SerenityS/MyPIU/blob/82aba360751bef620edf6a22c4a710415284231a/lib/presentation/play_data/view_models/my_data_view_model.dart#L33

해당 로직에서 코옵 채보를 10레벨 이하의 채보로 간주하여 totalClearCount에 반영하지 않아 문제가 발생하는 것으로 예상됩니다.

처음엔 Single, Double 채보만을 위해 구상된 ChartData라는 엔티티를
주변의 요청으로 다른 유형의 채보(UCS, COOP, ...)까지 지원하기 위해 Hack에 가까운 방법으로 호환 시키려다 문제가 발생 한 것 같습니다.

마침 오늘 디비전 예약이 있어서 코옵 플레이해보고 확실하게 수정 후 배포하면 될 것 같네요. 제가 편식이 심해서 더블만 하다보니 ㅎㅎ;

감사합니다!
